### PR TITLE
Fixed double request for last calls

### PR DESCRIPTION
**Pull request by tonyco97**
Solved multiple api calls of latest calls for nethvoice-cti user

### CODE REVIEW

**Review by gsanchietti — CHANGES_REQUESTED** [review]
Do not commit commented code: just remove it.
If you need to revert it, git will keep the old version for you.

**Comment by tonyco97** [comment]
> Do not commit commented code: just remove it. If you need to revert it, git will keep the old version for you.



> Do not commit commented code: just remove it. If you need to revert it, git will keep the old version for you.

Solved in the newer commit

**Comment by gsanchietti** [comment]
I'm removing myself as reviews. Formally the PR seems good, but we still miss a description.

Please explain the current behavior and the fix inside the PR description or, better, inside the commit body

**Review by gsanchietti — COMMENTED** [review]
I'm removing myself as reviwer. Formally the PR seems good, but we still miss a description.

Please explain the current behavior and the fix inside the PR description or, better, inside the commit body

**Review by edospadoni — APPROVED** [review]

**Pull request merged**
